"""added mixin fields in models

Revision ID: 2762bd905478
Revises: 1d3804d442bf
Create Date: 2025-10-31 22:48:12.918157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2762bd905478'
down_revision: Union[str, None] = '1d3804d442bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklist', ['token'])
    op.add_column('comment', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True))
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True))
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True))
    op.add_column('tag', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'is_active')
    op.drop_column('tag', 'updated_at')
    op.drop_column('tag', 'created_at')
    op.drop_column('tag', 'is_active')
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'created_at')
    op.drop_column('post', 'is_active')
    op.drop_column('comment', 'updated_at')
    op.drop_column('comment', 'created_at')
    op.drop_column('comment', 'is_active')
    op.drop_constraint(None, 'blacklist', type_='unique')
    # ### end Alembic commands ###
