"""Added tag table

Revision ID: 2cbea652ba35
Revises: 8a7349b62895
Create Date: 2024-11-11 08:04:58.435687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbea652ba35'
down_revision: Union[str, None] = '8a7349b62895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklist', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blacklist', type_='unique')
    # ### end Alembic commands ###
